### ISSUE TITLE
Cannot connect to CSI driver server

### ISSUE THREAD

**Issue by lpabon** [thecodeteam/gocsi#33]
I have a CSI server using the gRPC API as shown https://github.com/libopenstorage/openstorage/blob/master/csi/csi.go#L103 . I cannot create a connection to this server unless I remove the rule `grpc.WithDialer` in https://github.com/thecodeteam/gocsi/blob/master/csc/main.go#L176 .

Do you know why?

**Comment by akutz** [comment]
Hi,

Nope, no clue. I’ll take a look though. I know CSC works against other CSI SPs however.

**Comment by lpabon** [comment]
Here is the exact error:

```

**Comment by akutz** [comment]
Hi @lpabon,

The above endpoint is invalid. The endpoint can be in the form of a file path to a sock file or it must adhere to Go's network address path: `tcp://127.0.0.1:PORT`

**Comment by lpabon** [comment]
Yep that works! thanks. That should be on the help screen for endpoint.
