### ISSUE TITLE
Broken online help link

### ISSUE THREAD

**Issue by darkowlzz** [thecodeteam/gocsi#86]
The online help link https://goo.gl/GBnreq in [gocsi.sh#L376](https://github.com/thecodeteam/gocsi/blob/master/gocsi.sh#L376) seems to be broken. It points to https://github.com/thecodeteam/gocsi/tree/master/csp, which doesn't exists anymore.

The content of `csp/README.md` seems to have moved into the main repo README with some changes, more of examples. I can create a PR if I know the correct online help link. :)

**Comment by akutz** [comment]
Hi @darkowlzz,

Thank you for your other two PRs as well as finding this issue. The link to which you refer was just the csp README as you inferred. Perhaps a new link to https://github.com/thecodeteam/gocsi#bootstrapping-a-storage-plug-in?
